export type User = {
    capid: number;
    first_name: string;
    last_name: string;
    middle_name?: string;
    email: string;
    avatar?: string;
    email_verified_at: string | null;
    home_unit: string;
    gender: string;
    date_of_birth: Date;
    age_at_start: number;
    age_at_end: number;
    height?: number;
    weight?: number;
    shirt_size?: string;
    member_type: string;
    expiration: Date;
    member_status: string;
    home_phone?: string;
    cell_phone?: string;
    address_1: string;
    address_2: string;
    city: string;
    state: string;
    zip_code: string;
    registration_status: string;
    is_staff: boolean;
    registration_id: number;
    comments?: string;
    emergency_contact_name?: string;
    emergency_contact_number?: string;
    cadet_parent_phone_primary?: string;
    cadet_parent_phone_secondary?: string;
    cadet_parent_email_primary?: string;
    cadet_parent_email_secondary?: string;
    unit_commander_name: string;
    unit_commander_email: string;
    wing_commander_name: string;
    wing_commander_email: string;
    is_pilot: boolean;
    dl_expiration?: Date;
    last_encampment?: Date;
    highest_o_ride?: number;
    aircraft_ground_handling?: Date;
    wing_runner?: Date;
    orm_basic?: Date;
    orm_intermediate?: Date;
    cppt_expiration?: Date;
    monthly_safety?: Date;
    icut?: Date;
    is_100?: Date;
    is_700?: Date;
    capt_116?: Date;
    capt_117_part_1?: Date;
    capt_117_part_2?: Date;
    capt_117_part_3?: Date;
    first_aid?: Date;
    invoice_id?: number;
    prices_id?: number;
    invoice_status?: string;
    registered_by?: string;
    created_at: string;
    updated_at: string;
    [key: string]: unknown;
};

export type Auth = {
    user: User;
};

export type TwoFactorConfigContent = {
    title: string;
    description: string;
    buttonText: string;
};
